export default [
  {
    id: 0,
    name: "Kess Game",
    description: "Kess & Board Game Website",
    image: "images/projects/portfolio1.jpg",
    tags: ["NextJS", "ExpressJS", "PostgreSQL", "Bootstrap"],
    liveview: "https://kessgame.com/",
    github: "/",
    alt: "Kess & Board Game Website",
  },
  {
    id: 1,
    name: "SOS",
    description: "About S.O.S. Private Security Company",
    image: "images/projects/portfolio2.jpg",
    tags: ["React", "ExpressJS", "MySQL","Bootstrap"],
    liveview: "https://sosprivatesecurity.com/",
    github: "/",
    alt: "About S.O.S. Private Security Company",
  },
  {
    id: 2,
    name: "Right Charge",
    description: "About Rightcharge Company",
    image: "images/projects/portfolio3.jpg",
    tags: ["React", "Django", "Bootstrap","MongoDB"],
    liveview: "https://rightcharge.co.uk/",
    github: "/",
    alt: "About Rightcharge Company",
  },
  {
    id: 3,
    name: "Yaku Ai",
    description: "NFT Market Place",
    image: "images/projects/portfolio4.jpg",
    tags: ["React", "Laravel", "TailwindCSS", "MySQL", "Blockchain"],
    liveview: "https://yaku.ai/home",
    github: "/",
    alt: "NFT Market Place",
  },
  {
    id: 4,
    name: "Aktren",
    description:
      "Online communication Website",
    image: "images/projects/portfolio5.jpg",
    tags: ["React", "Laravel", "Bootstrap", "MongoDB"],
    liveview: "https://aktren.pl/",
    github: "/",
    alt: "Online communication Website",
  },
];
